apiVersion: v1
kind: Service

metadata:
  name: prometheus
  #namespace: new
  labels:
    component: prometheus
  
spec:
  selector:
    componenet: prometheus
  
  ports:
    - port: 9090
      targetPort: 9090