trigger:
- "*"

schedules:
- cron: "6 11 * * *"
  displayName: Morning check
  branches:
    include:
    - main6
  always: true

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, check2!
  displayName: 'Run a one-line script'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'Schedule'))
- script: echo done
  displayName: 'Check to run'

