global:
  scrape_interval:  5s

scrape_configs:
  - job_name: 'fastapi-app'
    static_configs:
      - targets: [backend-app:8000]

  - job_name: 'prometheus'
    static_configs:
      - targets: [localhost:9090]

  - job_name: 'python app exporter'
    static_configs:
      - targets: [backend-app:8001]
  
  