apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels: 
        component: backend
    spec:
      containers:
        - name: app
          image: arafat1998/backend-app:v11.0
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: {{ .Values.app.dbhost }}
            - name: DB_PORT
              value:  {{ quote .Values.app.dbport }}
            - name: DB_NAME
              value: {{ .Values.app.dbname }}
            - name: DB_USER
              value: {{ .Values.app.dbuser }}
            - name: POSTGRES_PASSWORD
              value: {{ quote .Values.app.password }}
            - name: REDIS_URL 
              value: {{ .Values.app.dbredis }}