apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: {{ .Values.namespace }}
spec:
  selector:
    component: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 31515
  type: NodePort