apiVersion: v1
kind: Service
metadata: 
  name: backend-app
  labels: 
    component: backend
spec:
  type: ClusterIP
  selector:
    component: backend
  ports:
    - port: 8000
      targetPort: 8000
    