name: "Bandit Security Scan"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bandit-scan:
    name: Bandit Security Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version you need

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit
      run: bandit -r . -f json -o bandit-report.json --severity-level high --confidence-level high

    - name: Upload Bandit Report
      uses: actions/upload-artifact@v2
      with:
        name: bandit-report
        path: bandit-report.json
