name: Horusec Scanner

on:
  push:
    branches:
      - main

jobs:
  horusec-scan:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Horusec Install
        run: curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
      
      - name: Horusec generate
        run: horusec generate

      - name: Horusec Run
        run: |
            horusec start --disable-docker --config-file-path=horusec-config.json --output-format="json" --json-output-file="horusec-report.json" -p .
        shell: bash

    
      # Upload horusec-config.json as an artifact
      - name: Upload Horusec config as artifact
        uses: actions/upload-artifact@v2
        with:
          name: horusec-config
          path: horusec-config.json

      # Notify via Slack webhook
      - name: Send Slack notification with artifact link
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "The Horusec config file has been generated. You can download it from GitHub Actions Artifacts: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
