name: Horusec Scanner

on:
  push:
    branches:
      - main

jobs:
  horusec-scan:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Horusec Install
        run: curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
      
      - name: Horusec generate
        run: horusec generate

      - name: Horusec Run
        run: |
            horusec start --disable-docker --config-file-path=horusec-config.json --output-format="json" --json-output-file="horusec-report.json" -p .
        shell: bash

    
      - name: Send Horusec Report to Slack
        run: |
          REPORT=$(cat horusec-report.json)
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Horusec Report: \n\`\`\`${REPORT}\`\`\`\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
